/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import datos.MaterialDAO;
import datos.PrestamoDAO;
import datos.UsuarioDAO;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.EstadoMaterial;
import modelo.EstadoPrestamo;
import modelo.MaterialBibliografico;
import modelo.Prestamo;
import modelo.Usuario;

/**
 *
 * @author yarie
 */
public class PanelPrestamos extends javax.swing.JPanel {

    /**
     * Creates new form PanelPrestamos
     */
    public PanelPrestamos() {
        initComponents();
        cargarUsuarios();
        cargarMateriales();
        cargarTabla();

        jFormattedTextFieldFecha.setText(LocalDate.now().toString());
    }
    
    //Métodos para cargar los combo box 
    private void cargarUsuarios() {

        UsuarioDAO usuarioDAO = new UsuarioDAO();

        jcmbUsuario.removeAllItems();

        for (Usuario usuario : usuarioDAO.listar()) {
            jcmbUsuario.addItem(usuario);
        }
    }

    private void cargarMateriales() {

        MaterialDAO materialDAO = new MaterialDAO();

        jcmbMaterial.removeAllItems();

        for (MaterialBibliografico material : materialDAO.listar()) {

            if (material.getEstado() == EstadoMaterial.DISPONIBLE) {
                jcmbMaterial.addItem(material);
            }
        }
    }
    
    //Método para actualizar los comboBox
    public void actualizarCombos() {
        cargarUsuarios();
        cargarMateriales();
    }
    
    //Método para cargar la tabla
    public void cargarTabla() {

        DefaultTableModel modelo = (DefaultTableModel) jTablePrestamos.getModel();

        modelo.setRowCount(0);

        PrestamoDAO dao = new PrestamoDAO();

        for (Prestamo p : dao.listar()) {

            modelo.addRow(new Object[]{
                p.getUsuario().getNombre(),
                p.getMaterial().getTitulo(),
                p.getFechaPrestamo(),
                p.getFechaDevolucionPrevista(),
                p.getFechaDevolucionReal()
            });
        }
    }
    
    //Método para limpiar campos
    private void limpiarCampos() {

        jcmbUsuario.setSelectedIndex(0);
        jcmbMaterial.setSelectedIndex(0);
        jFormattedTextFieldFecha.setText("");

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblTitulo = new javax.swing.JLabel();
        jlblUsuario = new javax.swing.JLabel();
        jcmbUsuario = new javax.swing.JComboBox<>();
        jcmbMaterial = new javax.swing.JComboBox<>();
        jlblMaterial = new javax.swing.JLabel();
        jlblFecha = new javax.swing.JLabel();
        jFormattedTextFieldFecha = new javax.swing.JFormattedTextField();
        jBtnRegistrarPrestamo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePrestamos = new javax.swing.JTable();
        jBtnActualizarTabla = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblTitulo.setBackground(new java.awt.Color(41, 58, 38));
        jlblTitulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jlblTitulo.setForeground(new java.awt.Color(41, 58, 38));
        jlblTitulo.setText("Registro de Prestamos");
        add(jlblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 16, 208, -1));

        jlblUsuario.setBackground(new java.awt.Color(41, 58, 38));
        jlblUsuario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblUsuario.setForeground(new java.awt.Color(41, 58, 38));
        jlblUsuario.setText("Usuario:");
        add(jlblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 87, -1, -1));

        jcmbUsuario.setBackground(new java.awt.Color(41, 58, 38));
        jcmbUsuario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jcmbUsuario.setForeground(new java.awt.Color(255, 255, 255));
        add(jcmbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 84, 553, -1));

        jcmbMaterial.setBackground(new java.awt.Color(41, 58, 38));
        jcmbMaterial.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jcmbMaterial.setForeground(new java.awt.Color(255, 255, 255));
        add(jcmbMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 127, 553, -1));

        jlblMaterial.setBackground(new java.awt.Color(41, 58, 38));
        jlblMaterial.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblMaterial.setForeground(new java.awt.Color(41, 58, 38));
        jlblMaterial.setText("Material:");
        add(jlblMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 130, -1, -1));

        jlblFecha.setBackground(new java.awt.Color(41, 58, 38));
        jlblFecha.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblFecha.setForeground(new java.awt.Color(41, 58, 38));
        jlblFecha.setText("Fecha:");
        add(jlblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 173, -1, -1));

        jFormattedTextFieldFecha.setBackground(new java.awt.Color(41, 58, 38));
        jFormattedTextFieldFecha.setForeground(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jFormattedTextFieldFecha.setCaretColor(new java.awt.Color(41, 58, 38));
        jFormattedTextFieldFecha.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldFecha.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        add(jFormattedTextFieldFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 170, 151, -1));

        jBtnRegistrarPrestamo.setBackground(new java.awt.Color(41, 58, 38));
        jBtnRegistrarPrestamo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBtnRegistrarPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        jBtnRegistrarPrestamo.setText("Registrar Préstamo");
        jBtnRegistrarPrestamo.addActionListener(this::jBtnRegistrarPrestamoActionPerformed);
        add(jBtnRegistrarPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 213, 186, -1));

        jScrollPane1.setBackground(new java.awt.Color(41, 58, 38));

        jTablePrestamos.setBackground(new java.awt.Color(41, 58, 38));
        jTablePrestamos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTablePrestamos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTablePrestamos.setForeground(new java.awt.Color(255, 255, 255));
        jTablePrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Usuario", "Material", "Fecha", "Fecha devolucion prevista", "Fecha devolucion real"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePrestamos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 259, 728, 164));

        jBtnActualizarTabla.setBackground(new java.awt.Color(41, 58, 38));
        jBtnActualizarTabla.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBtnActualizarTabla.setForeground(new java.awt.Color(255, 255, 255));
        jBtnActualizarTabla.setText("Refrescar");
        jBtnActualizarTabla.addActionListener(this::jBtnActualizarTablaActionPerformed);
        add(jBtnActualizarTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 441, 186, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRegistrarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegistrarPrestamoActionPerformed
        
        try {

            UsuarioDAO usuarioDAO = new UsuarioDAO();
            MaterialDAO materialDAO = new MaterialDAO();
            PrestamoDAO prestamoDAO = new PrestamoDAO();

            Usuario usuario =
                (Usuario) jcmbUsuario.getSelectedItem();

            MaterialBibliografico material =
                (MaterialBibliografico) jcmbMaterial.getSelectedItem();
            
            if (prestamoDAO.contarPrestamosActivos(usuario.getId())>= usuario.obtenerLimitePrestamos()) {

                JOptionPane.showMessageDialog(
                        this,
                        "El usuario alcanzó el límite de préstamos."
                );

                return;
            }

            LocalDate fechaPrestamo = LocalDate.now();

            LocalDate fechaPrevista = fechaPrestamo.plusDays(15);

            Prestamo prestamo = new Prestamo(
                    0,
                    usuario,
                    material,
                    fechaPrestamo,
                    fechaPrevista,
                    null,
                    EstadoPrestamo.ACTIVO
            );

            if (prestamoDAO.registrar(prestamo)) {

                materialDAO.actualizarEstado(
                        material.getId(),
                        EstadoMaterial.PRESTADO
                );

                JOptionPane.showMessageDialog(
                        this,
                        "Préstamo registrado correctamente."
                );

                cargarTabla();
                cargarMateriales();
                limpiarCampos();

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "No se pudo registrar el préstamo."
                );
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error: " + e.getMessage()
            );
        }
    }//GEN-LAST:event_jBtnRegistrarPrestamoActionPerformed

    private void jBtnActualizarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnActualizarTablaActionPerformed
        cargarTabla();
        cargarUsuarios();
        cargarMateriales();
    }//GEN-LAST:event_jBtnActualizarTablaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnActualizarTabla;
    private javax.swing.JButton jBtnRegistrarPrestamo;
    private javax.swing.JFormattedTextField jFormattedTextFieldFecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePrestamos;
    private javax.swing.JComboBox<MaterialBibliografico> jcmbMaterial;
    private javax.swing.JComboBox<Usuario> jcmbUsuario;
    private javax.swing.JLabel jlblFecha;
    private javax.swing.JLabel jlblMaterial;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JLabel jlblUsuario;
    // End of variables declaration//GEN-END:variables
}
