/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import datos.MaterialDAO;
import datos.PrestamoDAO;
import datos.UsuarioDAO;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.EstadoMaterial;
import modelo.EstadoPrestamo;
import modelo.MaterialBibliografico;
import modelo.Prestamo;
import modelo.Usuario;

/**
 *
 * @author yarie
 */
public class PanelPrestamos extends javax.swing.JPanel {

    /**
     * Creates new form PanelPrestamos
     */
    public PanelPrestamos() {
        initComponents();
        cargarUsuarios();
        cargarMateriales();
        cargarTabla();

        jFormattedTextFieldFecha.setText(LocalDate.now().toString());
    }
    
    //Métodos para cargar los combo box 
    private void cargarUsuarios() {

        UsuarioDAO usuarioDAO = new UsuarioDAO();

        jcmbUsuario.removeAllItems();

        for (Usuario usuario : usuarioDAO.listar()) {
            jcmbUsuario.addItem(usuario.getNombre());
        }
    }

    private void cargarMateriales() {

        MaterialDAO materialDAO = new MaterialDAO();

        jcmbMaterial.removeAllItems();

        for (MaterialBibliografico material : materialDAO.listar()) {

            if (material.getEstado() == EstadoMaterial.DISPONIBLE) {
                jcmbMaterial.addItem(material.getTitulo());
            }
        }
    }
    
    //Método para cargar la tabla
    private void cargarTabla() {

        DefaultTableModel modelo = (DefaultTableModel) jTablePrestamos.getModel();

        modelo.setRowCount(0);

        PrestamoDAO dao = new PrestamoDAO();

        for (Prestamo p : dao.listar()) {

            modelo.addRow(new Object[]{
                p.getUsuario().getNombre(),
                p.getMaterial().getTitulo(),
                p.getFechaPrestamo()
            });
        }
    }
    
    //Método para limpiar controles
    private void limpiarCampos() {

        jcmbUsuario.setSelectedIndex(0);
        jcmbMaterial.setSelectedIndex(0);
        jFormattedTextFieldFecha.setText("");

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblTitulo = new javax.swing.JLabel();
        jlblUsuario = new javax.swing.JLabel();
        jcmbUsuario = new javax.swing.JComboBox<>();
        jcmbMaterial = new javax.swing.JComboBox<>();
        jlblMaterial = new javax.swing.JLabel();
        jlblFecha = new javax.swing.JLabel();
        jFormattedTextFieldFecha = new javax.swing.JFormattedTextField();
        jBtnRegistrarPrestamo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePrestamos = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jlblTitulo.setBackground(new java.awt.Color(41, 58, 38));
        jlblTitulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jlblTitulo.setForeground(new java.awt.Color(41, 58, 38));
        jlblTitulo.setText("Registro de Prestamos");

        jlblUsuario.setBackground(new java.awt.Color(41, 58, 38));
        jlblUsuario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblUsuario.setForeground(new java.awt.Color(41, 58, 38));
        jlblUsuario.setText("Usuario:");

        jcmbUsuario.setBackground(new java.awt.Color(41, 58, 38));
        jcmbUsuario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jcmbUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jcmbUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Null", "Libro ", "Revista" }));

        jcmbMaterial.setBackground(new java.awt.Color(41, 58, 38));
        jcmbMaterial.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jcmbMaterial.setForeground(new java.awt.Color(255, 255, 255));
        jcmbMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Null", "Libro ", "Revista" }));

        jlblMaterial.setBackground(new java.awt.Color(41, 58, 38));
        jlblMaterial.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblMaterial.setForeground(new java.awt.Color(41, 58, 38));
        jlblMaterial.setText("Material:");

        jlblFecha.setBackground(new java.awt.Color(41, 58, 38));
        jlblFecha.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblFecha.setForeground(new java.awt.Color(41, 58, 38));
        jlblFecha.setText("Fecha:");

        jFormattedTextFieldFecha.setBackground(new java.awt.Color(41, 58, 38));
        jFormattedTextFieldFecha.setForeground(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jFormattedTextFieldFecha.setCaretColor(new java.awt.Color(41, 58, 38));
        jFormattedTextFieldFecha.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldFecha.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jBtnRegistrarPrestamo.setBackground(new java.awt.Color(41, 58, 38));
        jBtnRegistrarPrestamo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBtnRegistrarPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        jBtnRegistrarPrestamo.setText("Registrar Préstamo");
        jBtnRegistrarPrestamo.addActionListener(this::jBtnRegistrarPrestamoActionPerformed);

        jScrollPane1.setBackground(new java.awt.Color(41, 58, 38));

        jTablePrestamos.setBackground(new java.awt.Color(41, 58, 38));
        jTablePrestamos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTablePrestamos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTablePrestamos.setForeground(new java.awt.Color(255, 255, 255));
        jTablePrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Usuario", "Material", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePrestamos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblMaterial)
                            .addComponent(jlblUsuario)
                            .addComponent(jlblFecha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jFormattedTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jcmbUsuario, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcmbMaterial, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(69, 69, 69))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jBtnRegistrarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jlblTitulo)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblUsuario)
                    .addComponent(jcmbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblMaterial)
                    .addComponent(jcmbMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblFecha)
                    .addComponent(jFormattedTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jBtnRegistrarPrestamo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRegistrarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegistrarPrestamoActionPerformed
        
        try {

            UsuarioDAO usuarioDAO = new UsuarioDAO();
            MaterialDAO materialDAO = new MaterialDAO();
            PrestamoDAO prestamoDAO = new PrestamoDAO();

            Usuario usuario = usuarioDAO.listar().get(jcmbUsuario.getSelectedIndex());
            MaterialBibliografico material = materialDAO.listar().get(jcmbMaterial.getSelectedIndex());

            if (prestamoDAO.contarPrestamosActivos(usuario.getId())>= usuario.obtenerLimitePrestamos()) {

                JOptionPane.showMessageDialog(
                        this,
                        "El usuario alcanzó el límite de préstamos."
                );

                return;
            }

            LocalDate fechaPrestamo = LocalDate.now();

            LocalDate fechaPrevista = fechaPrestamo.plusDays(15);

            Prestamo prestamo = new Prestamo(
                    0,
                    usuario,
                    material,
                    fechaPrestamo,
                    fechaPrevista,
                    null,
                    EstadoPrestamo.ACTIVO
            );

            if (prestamoDAO.registrar(prestamo)) {

                materialDAO.actualizarEstado(
                        material.getId(),
                        EstadoMaterial.PRESTADO
                );

                JOptionPane.showMessageDialog(
                        this,
                        "Préstamo registrado correctamente."
                );

                cargarTabla();
                cargarMateriales();
                limpiarCampos();

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "No se pudo registrar el préstamo."
                );
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error: " + e.getMessage()
            );
        }
    }//GEN-LAST:event_jBtnRegistrarPrestamoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnRegistrarPrestamo;
    private javax.swing.JFormattedTextField jFormattedTextFieldFecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePrestamos;
    private javax.swing.JComboBox<String> jcmbMaterial;
    private javax.swing.JComboBox<String> jcmbUsuario;
    private javax.swing.JLabel jlblFecha;
    private javax.swing.JLabel jlblMaterial;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JLabel jlblUsuario;
    // End of variables declaration//GEN-END:variables
}
