/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import datos.UsuarioDAO;
import modelo.Estudiante;
import modelo.Profesor;
import modelo.Usuario;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author yarie
 */
public class PanelUsuarios extends javax.swing.JPanel {
    
    private UsuarioDAO usuarioDAO = new UsuarioDAO();
    /**
     * Creates new form PanelUsuarios
     */
    public PanelUsuarios() {
        initComponents();
        cargarTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblNombre = new javax.swing.JLabel();
        jlblID = new javax.swing.JLabel();
        jlblCorreo = new javax.swing.JLabel();
        jlblTipo = new javax.swing.JLabel();
        jlblTitulo = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jtxtID = new javax.swing.JTextField();
        jtxtCorreo = new javax.swing.JTextField();
        jcmbTipo = new javax.swing.JComboBox<>();
        jBtnGuardar = new javax.swing.JButton();
        jBtnConsultar = new javax.swing.JButton();
        jBtnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jlblNombre.setBackground(new java.awt.Color(41, 58, 38));
        jlblNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblNombre.setForeground(new java.awt.Color(41, 58, 38));
        jlblNombre.setText("Nombre:");

        jlblID.setBackground(new java.awt.Color(41, 58, 38));
        jlblID.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblID.setForeground(new java.awt.Color(41, 58, 38));
        jlblID.setText("Identificación:");

        jlblCorreo.setBackground(new java.awt.Color(41, 58, 38));
        jlblCorreo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblCorreo.setForeground(new java.awt.Color(41, 58, 38));
        jlblCorreo.setText("Correo:");

        jlblTipo.setBackground(new java.awt.Color(41, 58, 38));
        jlblTipo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblTipo.setForeground(new java.awt.Color(41, 58, 38));
        jlblTipo.setText("Tipo Usuario:");

        jlblTitulo.setBackground(new java.awt.Color(41, 58, 38));
        jlblTitulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jlblTitulo.setForeground(new java.awt.Color(41, 58, 38));
        jlblTitulo.setText("Registro de Usuarios");

        jtxtNombre.setBackground(new java.awt.Color(41, 58, 38));
        jtxtNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jtxtID.setBackground(new java.awt.Color(41, 58, 38));
        jtxtID.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jtxtCorreo.setBackground(new java.awt.Color(41, 58, 38));
        jtxtCorreo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jcmbTipo.setBackground(new java.awt.Color(41, 58, 38));
        jcmbTipo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jcmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Null", "Profesor", "Estudiante" }));

        jBtnGuardar.setBackground(new java.awt.Color(41, 58, 38));
        jBtnGuardar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBtnGuardar.setText("Guardar");
        jBtnGuardar.addActionListener(this::jBtnGuardarActionPerformed);

        jBtnConsultar.setBackground(new java.awt.Color(41, 58, 38));
        jBtnConsultar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBtnConsultar.setText("Consultar");
        jBtnConsultar.addActionListener(this::jBtnConsultarActionPerformed);

        jBtnLimpiar.setBackground(new java.awt.Color(41, 58, 38));
        jBtnLimpiar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBtnLimpiar.setText("Limpiar");
        jBtnLimpiar.addActionListener(this::jBtnLimpiarActionPerformed);

        jScrollPane1.setBackground(new java.awt.Color(41, 58, 38));

        jTableUsuarios.setBackground(new java.awt.Color(41, 58, 38));
        jTableUsuarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableUsuarios.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTableUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Identificación", "Correo", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblNombre)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlblID)
                        .addComponent(jlblCorreo, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jlblTipo, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtCorreo)
                    .addComponent(jcmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtID)
                    .addComponent(jtxtNombre))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jBtnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblTitulo)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNombre)
                    .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblID)
                    .addComponent(jtxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCorreo)
                    .addComponent(jtxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTipo)
                    .addComponent(jcmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnGuardar)
                    .addComponent(jBtnConsultar)
                    .addComponent(jBtnLimpiar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
        
        String nombre = jtxtNombre.getText().trim();
        String identificacion = jtxtID.getText().trim();
        String correo = jtxtCorreo.getText().trim();
        String tipo = jcmbTipo.getSelectedItem().toString();

        if(nombre.isEmpty() || identificacion.isEmpty() || correo.isEmpty() // Si los campos estan vacios, muestra advertencia
                || tipo.equals("Null")){

            JOptionPane.showMessageDialog(this, "Complete todos los campos.");
            return;
        }
        
        Usuario existente = usuarioDAO.buscarPorIdentificacion(identificacion);

            // Validación de ID
            if(existente != null){

                    JOptionPane.showMessageDialog(this,
                            "Ya existe un usuario con esa identificación.");

                    return;
            }    
            
        Usuario usuario;
        
        //Se registra dependiendo si es estudiante o profesor
        if(tipo.equals("Estudiante")){
           
            usuario = new Estudiante(0, identificacion, nombre, correo, true);
            
        }else{
            
            usuario = new Profesor(0, identificacion, nombre, correo, true);
        }
        
        //Llama a el DAO
        if(usuarioDAO.registrar(usuario)){

            JOptionPane.showMessageDialog(this,
                    "Usuario registrado correctamente.");

            limpiarCampos();

            cargarTabla();

        }else{

            JOptionPane.showMessageDialog(this,
                    "No se pudo registrar el usuario.");
        }
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void jBtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimpiarActionPerformed
        
        limpiarCampos();
        
    }//GEN-LAST:event_jBtnLimpiarActionPerformed

    private void jBtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultarActionPerformed
        
        String identificacion = jtxtID.getText().trim();

        if (identificacion.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Ingrese una identificación.");
            return;
        }

        Usuario usuario =
                usuarioDAO.buscarPorIdentificacion(identificacion);

        if (usuario != null) {

            jtxtNombre.setText(usuario.getNombre());
            jtxtCorreo.setText(usuario.getCorreo());

            //identifica de qué clase es el objeto(profesor o estudiante).
            if (usuario instanceof Estudiante) {
                jcmbTipo.setSelectedItem("Estudiante");
            } else {
                jcmbTipo.setSelectedItem("Profesor");
            }

        } else {

            limpiarCampos();
            JOptionPane.showMessageDialog(this,
                    "Usuario no encontrado.");
        }
    }//GEN-LAST:event_jBtnConsultarActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnConsultar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jBtnLimpiar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuarios;
    private javax.swing.JComboBox<String> jcmbTipo;
    private javax.swing.JLabel jlblCorreo;
    private javax.swing.JLabel jlblID;
    private javax.swing.JLabel jlblNombre;
    private javax.swing.JLabel jlblTipo;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JTextField jtxtCorreo;
    private javax.swing.JTextField jtxtID;
    private javax.swing.JTextField jtxtNombre;
    // End of variables declaration//GEN-END:variables
    
    
    //Método para limpiar campos
    private void limpiarCampos(){

        jtxtNombre.setText("");
        jtxtID.setText("");
        jtxtCorreo.setText("");
        jcmbTipo.setSelectedIndex(0);
    
    }
    
    
    //Método para cargar la tabla
    private void cargarTabla(){

        DefaultTableModel modelo =
                (DefaultTableModel) jTableUsuarios.getModel();

        modelo.setRowCount(0);

        List<Usuario> lista = usuarioDAO.listar();

        for(Usuario usuario : lista){

            String tipo;

            if(usuario instanceof Estudiante){
                tipo = "Estudiante";
            }else{
                tipo = "Profesor";
            }

            modelo.addRow(new Object[]{
                usuario.getNombre(),
                usuario.getIdentificacion(),
                usuario.getCorreo(),
                tipo
            });
        }

    }
}
