/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import datos.PrestamoDAO;
import javax.swing.table.DefaultTableModel;
import modelo.Prestamo;
import modelo.EstadoPrestamo;
import datos.MaterialDAO;
import modelo.EstadoMaterial;
import modelo.MaterialBibliografico;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author yarie
 */
public class PanelDevoluciones extends javax.swing.JPanel {

    /**
     * Creates new form PanelDevoluciones
     */
    public PanelDevoluciones() {
        initComponents();
        cargarTabla();
    }
    
    //Método para cargar la tabla
    private void cargarTabla() {

        DefaultTableModel modelo = (DefaultTableModel) jTableDevoluciones.getModel();
        modelo.setRowCount(0);

        PrestamoDAO dao = new PrestamoDAO();

        for (Prestamo p : dao.listar()) {

            if (p.getEstado() == EstadoPrestamo.ACTIVO) {

                modelo.addRow(new Object[]{
                    p.getId(),
                    p.getUsuario().getNombre(),
                    p.getMaterial().getTitulo(),
                    p.getFechaPrestamo()
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDevoluciones = new javax.swing.JTable();
        jlblTitulo = new javax.swing.JLabel();
        jBtnRegistrarDevolución = new javax.swing.JButton();
        jBtnActualizarTabla = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(41, 58, 38));

        jTableDevoluciones.setAutoCreateRowSorter(true);
        jTableDevoluciones.setBackground(new java.awt.Color(41, 58, 38));
        jTableDevoluciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableDevoluciones.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTableDevoluciones.setForeground(new java.awt.Color(255, 255, 255));
        jTableDevoluciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Usuario", "Material", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableDevoluciones);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 104, 550, 278));

        jlblTitulo.setBackground(new java.awt.Color(41, 58, 38));
        jlblTitulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jlblTitulo.setForeground(new java.awt.Color(41, 58, 38));
        jlblTitulo.setText("Registro de devoluciones");
        add(jlblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 27, 237, -1));

        jBtnRegistrarDevolución.setBackground(new java.awt.Color(41, 58, 38));
        jBtnRegistrarDevolución.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBtnRegistrarDevolución.setForeground(new java.awt.Color(255, 255, 255));
        jBtnRegistrarDevolución.setText("Registrar devolución");
        jBtnRegistrarDevolución.addActionListener(this::jBtnRegistrarDevoluciónActionPerformed);
        add(jBtnRegistrarDevolución, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 186, -1));

        jBtnActualizarTabla.setBackground(new java.awt.Color(41, 58, 38));
        jBtnActualizarTabla.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBtnActualizarTabla.setForeground(new java.awt.Color(255, 255, 255));
        jBtnActualizarTabla.setText("Actualizar tabla");
        jBtnActualizarTabla.addActionListener(this::jBtnActualizarTablaActionPerformed);
        add(jBtnActualizarTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 186, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRegistrarDevoluciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegistrarDevoluciónActionPerformed
    
        int fila = jTableDevoluciones.getSelectedRow();

        if (fila == -1) {

            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione un préstamo."
            );

            return;
        }
        int idPrestamo = Integer.parseInt(jTableDevoluciones.getValueAt(fila, 0).toString());

        PrestamoDAO prestamoDAO = new PrestamoDAO();
        Prestamo prestamo = prestamoDAO.buscarPorId(idPrestamo);

        if (prestamo == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "No se encontró el préstamo."
            );

            return;
        }

        if (prestamoDAO.registrarDevolucion(
                idPrestamo,
                LocalDate.now())) {

            MaterialDAO materialDAO = new MaterialDAO();

            MaterialBibliografico material = prestamo.getMaterial();

            materialDAO.actualizarEstado(
                    material.getId(),
                    EstadoMaterial.DISPONIBLE
            );

            JOptionPane.showMessageDialog(
                    this,
                    "Devolución registrada correctamente."
            );
            cargarTabla();
            
        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo registrar la devolución."
            );
        }
    }//GEN-LAST:event_jBtnRegistrarDevoluciónActionPerformed

    private void jBtnActualizarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnActualizarTablaActionPerformed
        cargarTabla();
    }//GEN-LAST:event_jBtnActualizarTablaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnActualizarTabla;
    private javax.swing.JButton jBtnRegistrarDevolución;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDevoluciones;
    private javax.swing.JLabel jlblTitulo;
    // End of variables declaration//GEN-END:variables
}
