/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import datos.PrestamoDAO;
import javax.swing.table.DefaultTableModel;
import modelo.Prestamo;
import modelo.EstadoPrestamo;
import datos.MaterialDAO;
import modelo.EstadoMaterial;
import modelo.MaterialBibliografico;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author yarie
 */
public class PanelDevoluciones extends javax.swing.JPanel {

    /**
     * Creates new form PanelDevoluciones
     */
    public PanelDevoluciones() {
        initComponents();
        cargarTabla();
    }
    
    //Método para cargar la tabla
    private void cargarTabla() {

        DefaultTableModel modelo = (DefaultTableModel) jTableDevoluciones.getModel();
        modelo.setRowCount(0);

        PrestamoDAO dao = new PrestamoDAO();

        for (Prestamo p : dao.listar()) {

            if (p.getEstado() == EstadoPrestamo.ACTIVO) {

                modelo.addRow(new Object[]{
                    p.getId(),
                    p.getUsuario().getNombre(),
                    p.getMaterial().getTitulo(),
                    p.getFechaPrestamo()
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDevoluciones = new javax.swing.JTable();
        jlblTitulo = new javax.swing.JLabel();
        jBtnRegistrarDevolución = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(41, 58, 38));

        jTableDevoluciones.setBackground(new java.awt.Color(41, 58, 38));
        jTableDevoluciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableDevoluciones.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTableDevoluciones.setForeground(new java.awt.Color(255, 255, 255));
        jTableDevoluciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Usuario", "Material", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableDevoluciones);

        jlblTitulo.setBackground(new java.awt.Color(41, 58, 38));
        jlblTitulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jlblTitulo.setForeground(new java.awt.Color(41, 58, 38));
        jlblTitulo.setText("Registro de devoluciones");

        jBtnRegistrarDevolución.setBackground(new java.awt.Color(41, 58, 38));
        jBtnRegistrarDevolución.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBtnRegistrarDevolución.setForeground(new java.awt.Color(255, 255, 255));
        jBtnRegistrarDevolución.setText("Registrar devolución");
        jBtnRegistrarDevolución.addActionListener(this::jBtnRegistrarDevoluciónActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnRegistrarDevolución, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jlblTitulo)
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnRegistrarDevolución)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRegistrarDevoluciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegistrarDevoluciónActionPerformed
    
        int fila = jTableDevoluciones.getSelectedRow();

        if (fila == -1) {

            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione un préstamo."
            );

            return;
        }

        int idPrestamo =
                Integer.parseInt(
                        jTableDevoluciones.getValueAt(fila, 0).toString()
                );

        PrestamoDAO prestamoDAO = new PrestamoDAO();

        Prestamo prestamo = prestamoDAO.buscarPorId(idPrestamo);

        if (prestamo == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "No se encontró el préstamo."
            );

            return;
        }

        if (prestamoDAO.registrarDevolucion(
                idPrestamo,
                LocalDate.now())) {

            MaterialDAO materialDAO = new MaterialDAO();

            MaterialBibliografico material = prestamo.getMaterial();

            materialDAO.actualizarEstado(
                    material.getId(),
                    EstadoMaterial.DISPONIBLE
            );

            JOptionPane.showMessageDialog(
                    this,
                    "Devolución registrada correctamente."
            );

            cargarTabla();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo registrar la devolución."
            );
        }
    }//GEN-LAST:event_jBtnRegistrarDevoluciónActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnRegistrarDevolución;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDevoluciones;
    private javax.swing.JLabel jlblTitulo;
    // End of variables declaration//GEN-END:variables
}
