/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import datos.MaterialDAO;
import modelo.MaterialBibliografico;
import modelo.Libro;
import modelo.Revista;
import modelo.EstadoMaterial;
import modelo.TipoMaterial;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author yarie
 */
public class PanelMateriales extends javax.swing.JPanel {

    private MaterialDAO materialDAO = new MaterialDAO();
    /**
     * Creates new form PanelMateriales
     */
    public PanelMateriales() {
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnGuardar = new javax.swing.JButton();
        jlblCódigo = new javax.swing.JLabel();
        jBtnConsultar = new javax.swing.JButton();
        jlblTitulo2 = new javax.swing.JLabel();
        jBtnLimpiar = new javax.swing.JButton();
        jlblAutor = new javax.swing.JLabel();
        jlblAnio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMateriales = new javax.swing.JTable();
        jlblTitulo = new javax.swing.JLabel();
        jtxtCódigo = new javax.swing.JTextField();
        jtxtTitulo = new javax.swing.JTextField();
        jtxtAutor = new javax.swing.JTextField();
        jcmbTipo = new javax.swing.JComboBox<>();
        jlblTipo = new javax.swing.JLabel();
        jtxtAnio = new javax.swing.JTextField();
        jlblNumeroEdicion = new javax.swing.JLabel();
        jtxtNumeroEdicion = new javax.swing.JTextField();
        jtxtISBN = new javax.swing.JTextField();
        jlblISBN = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jBtnGuardar.setBackground(new java.awt.Color(41, 58, 38));
        jBtnGuardar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnGuardar.setText("Guardar");
        jBtnGuardar.addActionListener(this::jBtnGuardarActionPerformed);

        jlblCódigo.setBackground(new java.awt.Color(41, 58, 38));
        jlblCódigo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblCódigo.setForeground(new java.awt.Color(41, 58, 38));
        jlblCódigo.setText("Código");

        jBtnConsultar.setBackground(new java.awt.Color(41, 58, 38));
        jBtnConsultar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBtnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnConsultar.setText("Consultar");
        jBtnConsultar.addActionListener(this::jBtnConsultarActionPerformed);

        jlblTitulo2.setBackground(new java.awt.Color(41, 58, 38));
        jlblTitulo2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblTitulo2.setForeground(new java.awt.Color(41, 58, 38));
        jlblTitulo2.setText("Título:");

        jBtnLimpiar.setBackground(new java.awt.Color(41, 58, 38));
        jBtnLimpiar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBtnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnLimpiar.setText("Limpiar");
        jBtnLimpiar.addActionListener(this::jBtnLimpiarActionPerformed);

        jlblAutor.setBackground(new java.awt.Color(41, 58, 38));
        jlblAutor.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblAutor.setForeground(new java.awt.Color(41, 58, 38));
        jlblAutor.setText("Autor:");

        jlblAnio.setBackground(new java.awt.Color(41, 58, 38));
        jlblAnio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblAnio.setForeground(new java.awt.Color(41, 58, 38));
        jlblAnio.setText("Año:");

        jScrollPane1.setBackground(new java.awt.Color(41, 58, 38));

        jTableMateriales.setBackground(new java.awt.Color(41, 58, 38));
        jTableMateriales.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableMateriales.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTableMateriales.setForeground(new java.awt.Color(255, 255, 255));
        jTableMateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Título", "Autor", "Año", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMateriales);

        jlblTitulo.setBackground(new java.awt.Color(41, 58, 38));
        jlblTitulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jlblTitulo.setForeground(new java.awt.Color(41, 58, 38));
        jlblTitulo.setText("Registro de Materiales");

        jtxtCódigo.setBackground(new java.awt.Color(41, 58, 38));
        jtxtCódigo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtxtCódigo.setForeground(new java.awt.Color(255, 255, 255));

        jtxtTitulo.setBackground(new java.awt.Color(41, 58, 38));
        jtxtTitulo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtxtTitulo.setForeground(new java.awt.Color(255, 255, 255));

        jtxtAutor.setBackground(new java.awt.Color(41, 58, 38));
        jtxtAutor.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtxtAutor.setForeground(new java.awt.Color(255, 255, 255));

        jcmbTipo.setBackground(new java.awt.Color(41, 58, 38));
        jcmbTipo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jcmbTipo.setForeground(new java.awt.Color(255, 255, 255));
        jcmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Null", "Libro", "Revista" }));

        jlblTipo.setBackground(new java.awt.Color(41, 58, 38));
        jlblTipo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblTipo.setForeground(new java.awt.Color(41, 58, 38));
        jlblTipo.setText("Tipo:");

        jtxtAnio.setBackground(new java.awt.Color(41, 58, 38));
        jtxtAnio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtxtAnio.setForeground(new java.awt.Color(255, 255, 255));

        jlblNumeroEdicion.setBackground(new java.awt.Color(41, 58, 38));
        jlblNumeroEdicion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblNumeroEdicion.setForeground(new java.awt.Color(41, 58, 38));
        jlblNumeroEdicion.setText("Número de edición:");

        jtxtNumeroEdicion.setBackground(new java.awt.Color(41, 58, 38));
        jtxtNumeroEdicion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtxtNumeroEdicion.setForeground(new java.awt.Color(255, 255, 255));

        jtxtISBN.setBackground(new java.awt.Color(41, 58, 38));
        jtxtISBN.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtxtISBN.setForeground(new java.awt.Color(255, 255, 255));

        jlblISBN.setBackground(new java.awt.Color(41, 58, 38));
        jlblISBN.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblISBN.setForeground(new java.awt.Color(41, 58, 38));
        jlblISBN.setText("ISBN:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jBtnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(jlblISBN)
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jlblNumeroEdicion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtISBN)
                            .addComponent(jtxtNumeroEdicion)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jlblTipo)
                        .addGap(36, 36, 36)
                        .addComponent(jcmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblCódigo)
                            .addComponent(jlblAutor)
                            .addComponent(jlblAnio)
                            .addComponent(jlblTitulo2))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtAutor)
                            .addComponent(jtxtCódigo)
                            .addComponent(jtxtAnio)
                            .addComponent(jtxtTitulo))))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jlblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlblTitulo)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblCódigo)
                            .addComponent(jtxtCódigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblTitulo2)
                            .addComponent(jtxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblAutor)
                            .addComponent(jtxtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblAnio)
                            .addComponent(jtxtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblTipo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblISBN)
                            .addComponent(jtxtISBN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblNumeroEdicion)
                            .addComponent(jtxtNumeroEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnGuardar)
                    .addComponent(jBtnConsultar)
                    .addComponent(jBtnLimpiar))
                .addContainerGap(304, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed

        String codigo = jtxtCódigo.getText().trim();
        String titulo = jtxtTitulo.getText().trim();
        String autor = jtxtAutor.getText().trim();
        String tipo = jcmbTipo.getSelectedItem().toString();
        String isbn = jtxtISBN.getText().trim();
        String numeroTexto = jtxtNumeroEdicion.getText().trim();

        if (codigo.isEmpty() || titulo.isEmpty() || autor.isEmpty()
                || jtxtAnio.getText().trim().isEmpty()
                || tipo.equals("Null")) {

            JOptionPane.showMessageDialog(this,
                    "Complete todos los campos.");
            return;
        }

        int anio;
        try {
            anio = Integer.parseInt(jtxtAnio.getText().trim());
        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this,
                    "Ingrese un año válido.");
            return;
        }

        MaterialBibliografico existente = materialDAO.buscarPorCodigo(codigo);

        if (existente != null) {

            JOptionPane.showMessageDialog(this,
                    "Ya existe un material con ese código.");

            return;
        }

        MaterialBibliografico material;

        if (tipo.equals("Libro")) {

            if (isbn.isEmpty()) {

                JOptionPane.showMessageDialog(this,
                        "Ingrese el ISBN.");

                return;
            }
            material = new Libro(
                    0,
                    codigo,
                    titulo,
                    autor,
                    anio,
                    EstadoMaterial.DISPONIBLE,
                    isbn
            );

        } else {
            if (numeroTexto.isEmpty()) {

                JOptionPane.showMessageDialog(this,
                        "Ingrese el número de edición.");

                return;
            }

            int numeroEdicion;

            try {
                numeroEdicion = Integer.parseInt(numeroTexto);

            } catch (NumberFormatException e) {
                
                JOptionPane.showMessageDialog(this,
                        "Número de edición inválido.");

                return;
            }

            material = new Revista(
                    0,
                    codigo,
                    titulo,
                    autor,
                    anio,
                    EstadoMaterial.DISPONIBLE,
                    numeroEdicion
            );
        }

        if (materialDAO.registrar(material)) {

            JOptionPane.showMessageDialog(this,
                    "Material registrado correctamente.");

            limpiarCampos();

            cargarTabla();

        } else {
            JOptionPane.showMessageDialog(this,
                    "No se pudo registrar el material.");
        }
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void jBtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimpiarActionPerformed
         
        limpiarCampos();
         
    }//GEN-LAST:event_jBtnLimpiarActionPerformed

    private void jBtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultarActionPerformed
        
        String codigo = jtxtCódigo.getText().trim();

        if(codigo.isEmpty()){

            JOptionPane.showMessageDialog(this,
                    "Ingrese un código.");
            return;
        }

        MaterialBibliografico material = materialDAO.buscarPorCodigo(codigo);

        if(material != null){
            
            jtxtTitulo.setText(material.getTitulo());
            jtxtAutor.setText(material.getAutor());
            jtxtAnio.setText(String.valueOf(material.getAnio()));

            // Identifica de que clase es el objeto (Libro o revista)
            if(material instanceof Libro){

                jcmbTipo.setSelectedItem("Libro");
                Libro libro = (Libro) material;
                jtxtISBN.setText(libro.getIsbn());
                jtxtNumeroEdicion.setText(""); // Al no ser revista queda vacío

            }else{

                jcmbTipo.setSelectedItem("Revista");

                Revista revista = (Revista) material;
                jtxtNumeroEdicion.setText(
                        String.valueOf(revista.getNumeroEdicion()));
                jtxtISBN.setText("");// Al no ser libro queda vacío
            }
            
        }else{
            JOptionPane.showMessageDialog(this,
                    "Material no encontrado.");
        }
    }//GEN-LAST:event_jBtnConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnConsultar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jBtnLimpiar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMateriales;
    private javax.swing.JComboBox<String> jcmbTipo;
    private javax.swing.JLabel jlblAnio;
    private javax.swing.JLabel jlblAutor;
    private javax.swing.JLabel jlblCódigo;
    private javax.swing.JLabel jlblISBN;
    private javax.swing.JLabel jlblNumeroEdicion;
    private javax.swing.JLabel jlblTipo;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JLabel jlblTitulo2;
    private javax.swing.JTextField jtxtAnio;
    private javax.swing.JTextField jtxtAutor;
    private javax.swing.JTextField jtxtCódigo;
    private javax.swing.JTextField jtxtISBN;
    private javax.swing.JTextField jtxtNumeroEdicion;
    private javax.swing.JTextField jtxtTitulo;
    // End of variables declaration//GEN-END:variables

    //Método para limpiar campos
    private void limpiarCampos(){

        jtxtCódigo.setText("");
        jtxtTitulo.setText("");
        jtxtAutor.setText("");
        jtxtAnio.setText("");
        jtxtISBN.setText("");
        jtxtNumeroEdicion.setText("");

        jcmbTipo.setSelectedIndex(0);
    }
    
    //Método para cargar la tabla
    
    private void cargarTabla(){

       DefaultTableModel modelo =
               (DefaultTableModel) jTableMateriales.getModel();

       modelo.setRowCount(0);

       List<MaterialBibliografico> lista =
               materialDAO.listar();

       for(MaterialBibliografico material : lista){

           String tipo;
           if(material instanceof Libro){

               tipo = "Libro";

           }else{
               tipo = "Revista";
           }

           modelo.addRow(new Object[]{
               material.getCodigo(),
               material.getTitulo(),
               material.getAutor(),
               material.getAnio(),
               tipo
           });

       }

   }   
}
