/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import datos.MaterialDAO;
import modelo.MaterialBibliografico;
import modelo.Libro;
import modelo.Revista;
import modelo.EstadoMaterial;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author yarie
 */
public class PanelMateriales extends javax.swing.JPanel {

    private int idMaterialSeleccionado;
    private MaterialDAO materialDAO = new MaterialDAO();
    private EstadoMaterial estadoSeleccionado;
    /**
     * Creates new form PanelMateriales
     */
    public PanelMateriales() {
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnGuardar = new javax.swing.JButton();
        jlblCódigo = new javax.swing.JLabel();
        jBtnConsultar = new javax.swing.JButton();
        jlblTitulo2 = new javax.swing.JLabel();
        jBtnLimpiar = new javax.swing.JButton();
        jlblAutor = new javax.swing.JLabel();
        jlblAnio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMateriales = new javax.swing.JTable();
        jlblTitulo = new javax.swing.JLabel();
        jtxtCódigo = new javax.swing.JTextField();
        jtxtTitulo = new javax.swing.JTextField();
        jtxtAutor = new javax.swing.JTextField();
        jcmbTipo = new javax.swing.JComboBox<>();
        jlblTipo = new javax.swing.JLabel();
        jtxtAnio = new javax.swing.JTextField();
        jlblNumeroEdicion = new javax.swing.JLabel();
        jtxtNumeroEdicion = new javax.swing.JTextField();
        jtxtISBN = new javax.swing.JTextField();
        jlblISBN = new javax.swing.JLabel();
        jBtnEliminar = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnGuardar.setBackground(new java.awt.Color(41, 58, 38));
        jBtnGuardar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnGuardar.setText("Guardar");
        jBtnGuardar.addActionListener(this::jBtnGuardarActionPerformed);
        add(jBtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 117, -1));

        jlblCódigo.setBackground(new java.awt.Color(41, 58, 38));
        jlblCódigo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblCódigo.setForeground(new java.awt.Color(41, 58, 38));
        jlblCódigo.setText("Código");
        add(jlblCódigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 70, -1, -1));

        jBtnConsultar.setBackground(new java.awt.Color(41, 58, 38));
        jBtnConsultar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBtnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnConsultar.setText("Consultar");
        jBtnConsultar.addActionListener(this::jBtnConsultarActionPerformed);
        add(jBtnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 117, -1));

        jlblTitulo2.setBackground(new java.awt.Color(41, 58, 38));
        jlblTitulo2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblTitulo2.setForeground(new java.awt.Color(41, 58, 38));
        jlblTitulo2.setText("Título:");
        add(jlblTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 113, -1, -1));

        jBtnLimpiar.setBackground(new java.awt.Color(41, 58, 38));
        jBtnLimpiar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBtnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnLimpiar.setText("Limpiar");
        jBtnLimpiar.addActionListener(this::jBtnLimpiarActionPerformed);
        add(jBtnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 117, -1));

        jlblAutor.setBackground(new java.awt.Color(41, 58, 38));
        jlblAutor.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblAutor.setForeground(new java.awt.Color(41, 58, 38));
        jlblAutor.setText("Autor:");
        add(jlblAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 156, -1, -1));

        jlblAnio.setBackground(new java.awt.Color(41, 58, 38));
        jlblAnio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblAnio.setForeground(new java.awt.Color(41, 58, 38));
        jlblAnio.setText("Año:");
        add(jlblAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 199, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(41, 58, 38));

        jTableMateriales.setBackground(new java.awt.Color(41, 58, 38));
        jTableMateriales.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableMateriales.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTableMateriales.setForeground(new java.awt.Color(255, 255, 255));
        jTableMateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Código", "Título", "Autor", "Año", "Tipo", "ISBN", "N.°Edición", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMateriales);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 600, 390));

        jlblTitulo.setBackground(new java.awt.Color(41, 58, 38));
        jlblTitulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jlblTitulo.setForeground(new java.awt.Color(41, 58, 38));
        jlblTitulo.setText("Registro de Materiales");
        add(jlblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 14, 208, -1));

        jtxtCódigo.setBackground(new java.awt.Color(41, 58, 38));
        jtxtCódigo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtxtCódigo.setForeground(new java.awt.Color(255, 255, 255));
        add(jtxtCódigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 67, 209, -1));

        jtxtTitulo.setBackground(new java.awt.Color(41, 58, 38));
        jtxtTitulo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtxtTitulo.setForeground(new java.awt.Color(255, 255, 255));
        add(jtxtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 110, 209, -1));

        jtxtAutor.setBackground(new java.awt.Color(41, 58, 38));
        jtxtAutor.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtxtAutor.setForeground(new java.awt.Color(255, 255, 255));
        add(jtxtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 153, 209, -1));

        jcmbTipo.setBackground(new java.awt.Color(41, 58, 38));
        jcmbTipo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jcmbTipo.setForeground(new java.awt.Color(255, 255, 255));
        jcmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Null", "Libro", "Revista" }));
        jcmbTipo.addActionListener(this::jcmbTipoActionPerformed);
        add(jcmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 239, 206, -1));

        jlblTipo.setBackground(new java.awt.Color(41, 58, 38));
        jlblTipo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblTipo.setForeground(new java.awt.Color(41, 58, 38));
        jlblTipo.setText("Tipo:");
        add(jlblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 242, -1, -1));

        jtxtAnio.setBackground(new java.awt.Color(41, 58, 38));
        jtxtAnio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtxtAnio.setForeground(new java.awt.Color(255, 255, 255));
        add(jtxtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 196, 209, -1));

        jlblNumeroEdicion.setBackground(new java.awt.Color(41, 58, 38));
        jlblNumeroEdicion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblNumeroEdicion.setForeground(new java.awt.Color(41, 58, 38));
        jlblNumeroEdicion.setText("Número de edición:");
        add(jlblNumeroEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 328, -1, -1));

        jtxtNumeroEdicion.setBackground(new java.awt.Color(41, 58, 38));
        jtxtNumeroEdicion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtxtNumeroEdicion.setForeground(new java.awt.Color(255, 255, 255));
        add(jtxtNumeroEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 325, 208, -1));

        jtxtISBN.setBackground(new java.awt.Color(41, 58, 38));
        jtxtISBN.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtxtISBN.setForeground(new java.awt.Color(255, 255, 255));
        add(jtxtISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 282, 208, -1));

        jlblISBN.setBackground(new java.awt.Color(41, 58, 38));
        jlblISBN.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblISBN.setForeground(new java.awt.Color(41, 58, 38));
        jlblISBN.setText("ISBN:");
        add(jlblISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 282, -1, -1));

        jBtnEliminar.setBackground(new java.awt.Color(41, 58, 38));
        jBtnEliminar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnEliminar.setText("Eliminar");
        jBtnEliminar.addActionListener(this::jBtnEliminarActionPerformed);
        add(jBtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 117, -1));

        jBtnEditar.setBackground(new java.awt.Color(41, 58, 38));
        jBtnEditar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBtnEditar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnEditar.setText("Editar");
        jBtnEditar.addActionListener(this::jBtnEditarActionPerformed);
        add(jBtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 117, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed

        String codigo = jtxtCódigo.getText().trim();
        String titulo = jtxtTitulo.getText().trim();
        String autor = jtxtAutor.getText().trim();
        String tipo = jcmbTipo.getSelectedItem().toString();
        String isbn = jtxtISBN.getText().trim();
        String numeroTexto = jtxtNumeroEdicion.getText().trim();

        if (codigo.isEmpty() || titulo.isEmpty() || autor.isEmpty()
                || jtxtAnio.getText().trim().isEmpty()
                || tipo.equals("Null")) {

            JOptionPane.showMessageDialog(this,
                    "Complete todos los campos.");
            return;
        }

        int anio;
        try {
            anio = Integer.parseInt(jtxtAnio.getText().trim());
        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this,
                    "Ingrese un año válido.");
            return;
        }

        MaterialBibliografico existente = materialDAO.buscarPorCodigo(codigo);

        if (existente != null) {

            JOptionPane.showMessageDialog(this,
                    "Ya existe un material con ese código.");

            return;
        }
        MaterialBibliografico material;

        if (tipo.equals("Libro")) {

            if (isbn.isEmpty()) {

                JOptionPane.showMessageDialog(this,
                        "Ingrese el ISBN.");

                return;
            }
            material = new Libro(
                    0,
                    codigo,
                    titulo,
                    autor,
                    anio,
                    EstadoMaterial.DISPONIBLE,
                    isbn
            );
        } else {
            if (numeroTexto.isEmpty()) {

                JOptionPane.showMessageDialog(this,
                        "Ingrese el número de edición.");

                return;
            }
            int numeroEdicion;

            try {
                numeroEdicion = Integer.parseInt(numeroTexto);

            } catch (NumberFormatException e) {
                
                JOptionPane.showMessageDialog(this,
                        "Número de edición inválido.");
                return;
            }
            material = new Revista(
                    0,
                    codigo,
                    titulo,
                    autor,
                    anio,
                    EstadoMaterial.DISPONIBLE,
                    numeroEdicion
            );
        }

        if (materialDAO.registrar(material)) {

            JOptionPane.showMessageDialog(this,
                    "Material registrado correctamente.");

            limpiarCampos();

            cargarTabla();

        } else {
            JOptionPane.showMessageDialog(this,
                    "No se pudo registrar el material.");
        }
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void jBtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimpiarActionPerformed
         
        limpiarCampos();
         
    }//GEN-LAST:event_jBtnLimpiarActionPerformed

    private void jBtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultarActionPerformed
        
        String codigo = jtxtCódigo.getText().trim();

        if(codigo.isEmpty()){

            JOptionPane.showMessageDialog(this,
                    "Ingrese un código.");
            return;
        }

        MaterialBibliografico material = materialDAO.buscarPorCodigo(codigo);
        idMaterialSeleccionado = material.getId();
        estadoSeleccionado = material.getEstado();

        if(material != null){
            
            jtxtTitulo.setText(material.getTitulo());
            jtxtAutor.setText(material.getAutor());
            jtxtAnio.setText(String.valueOf(material.getAnio()));

            // Identifica de que clase es el objeto (Libro o revista)
            if(material instanceof Libro){

                jcmbTipo.setSelectedItem("Libro");
                Libro libro = (Libro) material;
                jtxtISBN.setText(libro.getIsbn());
                jtxtNumeroEdicion.setText(""); // Al no ser revista queda vacío

            }else{

                jcmbTipo.setSelectedItem("Revista");

                Revista revista = (Revista) material;
                jtxtNumeroEdicion.setText(
                        String.valueOf(revista.getNumeroEdicion()));
                jtxtISBN.setText("");// Al no ser libro queda vacío
            }
            
        }else{
            JOptionPane.showMessageDialog(this,
                    "Material no encontrado.");
        }
    }//GEN-LAST:event_jBtnConsultarActionPerformed

    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed
    
        int fila = jTableMateriales.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione un material.");
            return;
        }

        int idMaterial = (int) jTableMateriales.getValueAt(fila, 0);

        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Desea eliminar este material?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {

            if (materialDAO.eliminar(idMaterial)) {

                JOptionPane.showMessageDialog(this,
                        "Material eliminado correctamente.");

                cargarTabla();
                limpiarCampos();
               

            } else {

                JOptionPane.showMessageDialog(this,
                        "No se pudo eliminar el material.");
            }
        }
    }//GEN-LAST:event_jBtnEliminarActionPerformed

    private void jcmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbTipoActionPerformed
        // Así estará habilitado el campo de texto si es libro o revista
        if (jcmbTipo.getSelectedItem().equals("Libro")) {

            jtxtISBN.setEnabled(true);
            jtxtNumeroEdicion.setEnabled(false);
            jtxtNumeroEdicion.setText("");

        } else if (jcmbTipo.getSelectedItem().equals("Revista")) {

            jtxtISBN.setEnabled(false);
            jtxtISBN.setText("");

            jtxtNumeroEdicion.setEnabled(true);
        }
    }//GEN-LAST:event_jcmbTipoActionPerformed

    private void jBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarActionPerformed
        
        String codigo = jtxtCódigo.getText().trim();
        String titulo = jtxtTitulo.getText().trim();
        String autor = jtxtAutor.getText().trim();

        int anio = Integer.parseInt(jtxtAnio.getText());

        String tipo = jcmbTipo.getSelectedItem().toString();

        MaterialBibliografico material;

        if(tipo.equals("Libro")) {

            material = new Libro(
                    idMaterialSeleccionado,
                    codigo,
                    titulo,
                    autor,
                    anio,
                    estadoSeleccionado,
                    jtxtISBN.getText()
            );
        } else {

            material = new Revista(
                    idMaterialSeleccionado,
                    codigo,
                    titulo,
                    autor,
                    anio,
                    estadoSeleccionado,
                    Integer.parseInt(jtxtNumeroEdicion.getText())
            );
        }
        if(materialDAO.actualizar(material)) {

            JOptionPane.showMessageDialog(this,
                    "Material actualizado correctamente.");

            cargarTabla();
            limpiarCampos();

        } else {
            JOptionPane.showMessageDialog(this,
                    "No se pudo actualizar.");
        }
    }//GEN-LAST:event_jBtnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnConsultar;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jBtnLimpiar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMateriales;
    private javax.swing.JComboBox<String> jcmbTipo;
    private javax.swing.JLabel jlblAnio;
    private javax.swing.JLabel jlblAutor;
    private javax.swing.JLabel jlblCódigo;
    private javax.swing.JLabel jlblISBN;
    private javax.swing.JLabel jlblNumeroEdicion;
    private javax.swing.JLabel jlblTipo;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JLabel jlblTitulo2;
    private javax.swing.JTextField jtxtAnio;
    private javax.swing.JTextField jtxtAutor;
    private javax.swing.JTextField jtxtCódigo;
    private javax.swing.JTextField jtxtISBN;
    private javax.swing.JTextField jtxtNumeroEdicion;
    private javax.swing.JTextField jtxtTitulo;
    // End of variables declaration//GEN-END:variables

    //Método para limpiar campos
    private void limpiarCampos(){

        jtxtCódigo.setText("");
        jtxtTitulo.setText("");
        jtxtAutor.setText("");
        jtxtAnio.setText("");
        jtxtISBN.setText("");
        jtxtNumeroEdicion.setText("");

        jcmbTipo.setSelectedIndex(0);
    }
    
    //Método para cargar la tabla
    
    private void cargarTabla(){

       DefaultTableModel modelo =
               (DefaultTableModel) jTableMateriales.getModel();

       modelo.setRowCount(0);

       List<MaterialBibliografico> lista =
               materialDAO.listar();

       for(MaterialBibliografico material : lista){

           String tipo;
           if(material instanceof Libro){

               tipo = "Libro";

           }else{
               tipo = "Revista";
           }

           modelo.addRow(new Object[]{
               material.getId(),
               material.getCodigo(),
               material.getTitulo(),
               material.getAutor(),
               material.getAnio(),
               tipo,
               // Comprueba si el objeto es de esa clase o si hereda de ella.
               material instanceof Libro ? ((Libro) material).getIsbn() : "",
               material instanceof Revista ? ((Revista) material).getNumeroEdicion() : "",
               material.getEstado()
           });
       }
   }   
}
