/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import datos.UsuarioDAO;
import modelo.Estudiante;
import modelo.Profesor;
import modelo.Usuario;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author yarie
 */
public class PanelUsuarios extends javax.swing.JPanel {
    

    private UsuarioDAO usuarioDAO = new UsuarioDAO();
    /**
     * Creates new form PanelUsuarios
     */
    public PanelUsuarios() {
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblNombre = new javax.swing.JLabel();
        jlblID = new javax.swing.JLabel();
        jlblCorreo = new javax.swing.JLabel();
        jlblTipo = new javax.swing.JLabel();
        jlblTitulo = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jtxtID = new javax.swing.JTextField();
        jtxtCorreo = new javax.swing.JTextField();
        jcmbTipo = new javax.swing.JComboBox<>();
        jBtnGuardar = new javax.swing.JButton();
        jBtnConsultar = new javax.swing.JButton();
        jBtnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();
        jlblActivo = new javax.swing.JLabel();
        jCbxActivo = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblNombre.setBackground(new java.awt.Color(41, 58, 38));
        jlblNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblNombre.setForeground(new java.awt.Color(41, 58, 38));
        jlblNombre.setText("Nombre:");
        add(jlblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 67, -1, -1));

        jlblID.setBackground(new java.awt.Color(41, 58, 38));
        jlblID.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblID.setForeground(new java.awt.Color(41, 58, 38));
        jlblID.setText("Identificación:");
        add(jlblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 110, -1, -1));

        jlblCorreo.setBackground(new java.awt.Color(41, 58, 38));
        jlblCorreo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblCorreo.setForeground(new java.awt.Color(41, 58, 38));
        jlblCorreo.setText("Correo:");
        add(jlblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 153, -1, -1));

        jlblTipo.setBackground(new java.awt.Color(41, 58, 38));
        jlblTipo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblTipo.setForeground(new java.awt.Color(41, 58, 38));
        jlblTipo.setText("Tipo Usuario:");
        add(jlblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 196, -1, -1));

        jlblTitulo.setBackground(new java.awt.Color(41, 58, 38));
        jlblTitulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jlblTitulo.setForeground(new java.awt.Color(41, 58, 38));
        jlblTitulo.setText("Registro de Usuarios");
        add(jlblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 6, 208, -1));

        jtxtNombre.setBackground(new java.awt.Color(41, 58, 38));
        jtxtNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtxtNombre.setForeground(new java.awt.Color(255, 255, 255));
        add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 64, 350, -1));

        jtxtID.setBackground(new java.awt.Color(41, 58, 38));
        jtxtID.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtxtID.setForeground(new java.awt.Color(255, 255, 255));
        add(jtxtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 107, 350, -1));

        jtxtCorreo.setBackground(new java.awt.Color(41, 58, 38));
        jtxtCorreo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtxtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        add(jtxtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 350, -1));

        jcmbTipo.setBackground(new java.awt.Color(41, 58, 38));
        jcmbTipo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jcmbTipo.setForeground(new java.awt.Color(255, 255, 255));
        jcmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Null", "Profesor", "Estudiante" }));
        add(jcmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 193, 350, -1));

        jBtnGuardar.setBackground(new java.awt.Color(41, 58, 38));
        jBtnGuardar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnGuardar.setText("Guardar");
        jBtnGuardar.addActionListener(this::jBtnGuardarActionPerformed);
        add(jBtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 277, 117, -1));

        jBtnConsultar.setBackground(new java.awt.Color(41, 58, 38));
        jBtnConsultar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBtnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnConsultar.setText("Consultar");
        jBtnConsultar.addActionListener(this::jBtnConsultarActionPerformed);
        add(jBtnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 277, 117, -1));

        jBtnLimpiar.setBackground(new java.awt.Color(41, 58, 38));
        jBtnLimpiar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBtnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnLimpiar.setText("Limpiar");
        jBtnLimpiar.addActionListener(this::jBtnLimpiarActionPerformed);
        add(jBtnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 277, 117, -1));

        jScrollPane1.setBackground(new java.awt.Color(41, 58, 38));

        jTableUsuarios.setBackground(new java.awt.Color(41, 58, 38));
        jTableUsuarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableUsuarios.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTableUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Identificación", "Correo", "Tipo", "Activo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableUsuarios);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 321, 620, 271));

        jlblActivo.setBackground(new java.awt.Color(41, 58, 38));
        jlblActivo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblActivo.setForeground(new java.awt.Color(41, 58, 38));
        jlblActivo.setText("Activo:");
        add(jlblActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 238, -1, -1));

        jCbxActivo.setBackground(new java.awt.Color(255, 255, 255));
        jCbxActivo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCbxActivo.setForeground(new java.awt.Color(41, 58, 38));
        jCbxActivo.setText("Si");
        add(jCbxActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 236, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
        
        String nombre = jtxtNombre.getText().trim();
        String identificacion = jtxtID.getText().trim();
        String correo = jtxtCorreo.getText().trim();
        String tipo = jcmbTipo.getSelectedItem().toString();

        if(nombre.isEmpty() || identificacion.isEmpty() || correo.isEmpty() // Si los campos estan vacios, muestra advertencia
                || tipo.equals("Null")){

            JOptionPane.showMessageDialog(this, "Complete todos los campos.");
            return;
        }
        
        Usuario existente = usuarioDAO.buscarPorIdentificacion(identificacion);

            // Validación de ID
            if(existente != null){

                    JOptionPane.showMessageDialog(this,
                            "Ya existe un usuario con esa identificación.");

                    return;
            }    
            
        Usuario usuario;
        
        //Se registra dependiendo si es estudiante o profesor
        if(tipo.equals("Estudiante")){
           
            usuario = new Estudiante(0, identificacion, nombre, correo, true);
            
        }else{
            
            usuario = new Profesor(0, identificacion, nombre, correo, true);
        }
        
        //Llama a el DAO
        if(usuarioDAO.registrar(usuario)){

            JOptionPane.showMessageDialog(this,
                    "Usuario registrado correctamente.");

            limpiarCampos();

            cargarTabla();

        }else{

            JOptionPane.showMessageDialog(this,
                    "No se pudo registrar el usuario.");
        }
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void jBtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimpiarActionPerformed
        
        limpiarCampos();
        
    }//GEN-LAST:event_jBtnLimpiarActionPerformed

    private void jBtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultarActionPerformed
        
        String identificacion = jtxtID.getText().trim();

        if (identificacion.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Ingrese una identificación.");
            return;
        }

        Usuario usuario = usuarioDAO.buscarPorIdentificacion(identificacion);

        if (usuario != null) {

            jtxtNombre.setText(usuario.getNombre());
            jtxtCorreo.setText(usuario.getCorreo());

            //identifica de qué clase es el objeto(profesor o estudiante).
            if (usuario instanceof Estudiante) {
                jcmbTipo.setSelectedItem("Estudiante");
            } else {
                jcmbTipo.setSelectedItem("Profesor");
            }

        } else {

            limpiarCampos();
            JOptionPane.showMessageDialog(this,
                    "Usuario no encontrado.");
        }
    }//GEN-LAST:event_jBtnConsultarActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnConsultar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jBtnLimpiar;
    private javax.swing.JCheckBox jCbxActivo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuarios;
    private javax.swing.JComboBox<String> jcmbTipo;
    private javax.swing.JLabel jlblActivo;
    private javax.swing.JLabel jlblCorreo;
    private javax.swing.JLabel jlblID;
    private javax.swing.JLabel jlblNombre;
    private javax.swing.JLabel jlblTipo;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JTextField jtxtCorreo;
    private javax.swing.JTextField jtxtID;
    private javax.swing.JTextField jtxtNombre;
    // End of variables declaration//GEN-END:variables
    
    
    //Método para limpiar campos
    private void limpiarCampos(){

        jtxtNombre.setText("");
        jtxtID.setText("");
        jtxtCorreo.setText("");
        jcmbTipo.setSelectedIndex(0);
    
    }
    
    
    //Método para cargar la tabla
    private void cargarTabla(){

        DefaultTableModel modelo =
                (DefaultTableModel) jTableUsuarios.getModel();

        modelo.setRowCount(0);

        List<Usuario> lista = usuarioDAO.listar();

        for(Usuario usuario : lista){

            String tipo;

            if(usuario instanceof Estudiante){
                tipo = "Estudiante";
            }else{
                tipo = "Profesor";
            }

            modelo.addRow(new Object[]{
                usuario.getNombre(),
                usuario.getIdentificacion(),
                usuario.getCorreo(),
                tipo,
                usuario.isActivo()
            });
        }

    }
}
