/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

/**
 *
 * @author yarie
 */
public class PanelMateriales extends javax.swing.JPanel {

    /**
     * Creates new form PanelMateriales
     */
    public PanelMateriales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnGuardar = new javax.swing.JButton();
        jlblCódigo = new javax.swing.JLabel();
        jBtnConsultar = new javax.swing.JButton();
        jlblTitulo2 = new javax.swing.JLabel();
        jBtnLimpiar = new javax.swing.JButton();
        jlblAutor = new javax.swing.JLabel();
        jlblAnio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMateriales = new javax.swing.JTable();
        jlblTitulo = new javax.swing.JLabel();
        jtxtCódigo = new javax.swing.JTextField();
        jtxtTitulo = new javax.swing.JTextField();
        jtxtAutor = new javax.swing.JTextField();
        jcmbTipo = new javax.swing.JComboBox<>();
        jlblTipo = new javax.swing.JLabel();
        jtxtAnio = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jBtnGuardar.setBackground(new java.awt.Color(41, 58, 38));
        jBtnGuardar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBtnGuardar.setText("Guardar");

        jlblCódigo.setBackground(new java.awt.Color(41, 58, 38));
        jlblCódigo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblCódigo.setForeground(new java.awt.Color(41, 58, 38));
        jlblCódigo.setText("Código");

        jBtnConsultar.setBackground(new java.awt.Color(41, 58, 38));
        jBtnConsultar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBtnConsultar.setText("Consultar");

        jlblTitulo2.setBackground(new java.awt.Color(41, 58, 38));
        jlblTitulo2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblTitulo2.setForeground(new java.awt.Color(41, 58, 38));
        jlblTitulo2.setText("Título:");

        jBtnLimpiar.setBackground(new java.awt.Color(41, 58, 38));
        jBtnLimpiar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBtnLimpiar.setText("Limpiar");

        jlblAutor.setBackground(new java.awt.Color(41, 58, 38));
        jlblAutor.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblAutor.setForeground(new java.awt.Color(41, 58, 38));
        jlblAutor.setText("Autor:");

        jlblAnio.setBackground(new java.awt.Color(41, 58, 38));
        jlblAnio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblAnio.setForeground(new java.awt.Color(41, 58, 38));
        jlblAnio.setText("Año:");

        jScrollPane1.setBackground(new java.awt.Color(41, 58, 38));

        jTableMateriales.setBackground(new java.awt.Color(41, 58, 38));
        jTableMateriales.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableMateriales.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTableMateriales.setForeground(new java.awt.Color(255, 255, 255));
        jTableMateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Título", "Autor", "Año", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMateriales);

        jlblTitulo.setBackground(new java.awt.Color(41, 58, 38));
        jlblTitulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jlblTitulo.setForeground(new java.awt.Color(41, 58, 38));
        jlblTitulo.setText("Registro de Materiales");

        jtxtCódigo.setBackground(new java.awt.Color(41, 58, 38));
        jtxtCódigo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jtxtTitulo.setBackground(new java.awt.Color(41, 58, 38));
        jtxtTitulo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jtxtAutor.setBackground(new java.awt.Color(41, 58, 38));
        jtxtAutor.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jcmbTipo.setBackground(new java.awt.Color(41, 58, 38));
        jcmbTipo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jcmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Null", "Libro ", "Revista" }));

        jlblTipo.setBackground(new java.awt.Color(41, 58, 38));
        jlblTipo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlblTipo.setForeground(new java.awt.Color(41, 58, 38));
        jlblTipo.setText("Tipo:");

        jtxtAnio.setBackground(new java.awt.Color(41, 58, 38));
        jtxtAnio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblCódigo)
                    .addComponent(jlblAutor)
                    .addComponent(jlblAnio)
                    .addComponent(jlblTitulo2)
                    .addComponent(jlblTipo))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtAutor)
                    .addComponent(jcmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtTitulo)
                    .addComponent(jtxtCódigo)
                    .addComponent(jtxtAnio))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jBtnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblTitulo)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCódigo)
                    .addComponent(jtxtCódigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTitulo2)
                    .addComponent(jtxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblAutor)
                    .addComponent(jtxtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblAnio)
                    .addComponent(jtxtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTipo)
                    .addComponent(jcmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnGuardar)
                    .addComponent(jBtnConsultar)
                    .addComponent(jBtnLimpiar))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnConsultar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jBtnLimpiar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMateriales;
    private javax.swing.JComboBox<String> jcmbTipo;
    private javax.swing.JLabel jlblAnio;
    private javax.swing.JLabel jlblAutor;
    private javax.swing.JLabel jlblCódigo;
    private javax.swing.JLabel jlblTipo;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JLabel jlblTitulo2;
    private javax.swing.JTextField jtxtAnio;
    private javax.swing.JTextField jtxtAutor;
    private javax.swing.JTextField jtxtCódigo;
    private javax.swing.JTextField jtxtTitulo;
    // End of variables declaration//GEN-END:variables
}
